export const TTANSITION_DURING_SLOW = 300;
export const TTANSITION_DURING_BASE = 200;
export const TTANSITION_DURING_FAST = 100;
export const TTANSITION_DURING_POPUP = 116;

export const WINDOW_SPACE = 10;
