name: 'Tagged Release'

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, 'next') }}
